apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: dir-course-stats-consumer-sqs-egress
      namespace: dir-backend-ns
      labels: &labels
        app.kubernetes.io/part-of: dai-run
        dairun.io/change-scope: backend-sns-sqs
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/name: dir-course-stats-consumer
      policyTypes: [Egress]
      egress: &sqsEgress
        - to:
            - ipBlock: {cidr: 169.254.170.23/32}
          ports:
            - {protocol: TCP, port: 80}
        - to:
            - ipBlock: {cidr: 10.10.2.9/32}
            - ipBlock: {cidr: 10.10.5.157/32}
          ports:
            - {protocol: TCP, port: 443}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: dir-crew-consumer-sqs-egress
      namespace: dir-backend-ns
      labels: *labels
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/name: dir-crew-consumer
      policyTypes: [Egress]
      egress: *sqsEgress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: dir-crew-notification-consumer-sqs-egress
      namespace: dir-backend-ns
      labels: *labels
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/name: dir-crew-notification-consumer
      policyTypes: [Egress]
      egress: *sqsEgress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: dir-notification-consumer-sqs-egress
      namespace: dir-backend-ns
      labels: *labels
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/name: dir-notification-consumer
      policyTypes: [Egress]
      egress: *sqsEgress
