apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-backend-worker-shadow
  namespace: dir-backend-ns
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: dai-run
    dairun.io/change-scope: backend-db-shadow
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
