sonar.projectKey=dai-run-application
sonar.projectName=DAI RUN Application
sonar.sources=.
sonar.exclusions=.git/**,.scannerwork/**,ai-service/**,ci-output/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=ci-output/ai-dashboard-test/coverage/lcov.info

