apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dir-frontend-ns
resources:
  - configmap-dir-frontend-config.yaml
  - namespace.yaml
  - deployment-dir-frontend.yaml
  - service-dir-frontend-svc.yaml
  - hpa-dir-frontend-hpa.yaml
