apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dir-gitops-test-ns
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - deployment-green.yaml
  - service-green.yaml
  - deployment-auth-service.yaml
  - service-auth-service.yaml
  - deployment-auth-service-green.yaml
  - service-auth-service-green.yaml
  - deployment-auth-web.yaml
  - service-auth-web.yaml
  - deployment-auth-web-green.yaml
  - service-auth-web-green.yaml
  - deployment-challenge-service.yaml
  - service-challenge-service.yaml
  - deployment-challenge-service-green.yaml
  - service-challenge-service-green.yaml
  - deployment-coaching-service.yaml
  - service-coaching-service.yaml
  - deployment-coaching-service-green.yaml
  - service-coaching-service-green.yaml
  - deployment-course-recommendation-service.yaml
  - service-course-recommendation-service.yaml
  - deployment-course-recommendation-service-green.yaml
  - service-course-recommendation-service-green.yaml
  - deployment-course-service.yaml
  - service-course-service.yaml
  - deployment-course-service-green.yaml
  - service-course-service-green.yaml
  - deployment-crew-service.yaml
  - service-crew-service.yaml
  - deployment-crew-service-green.yaml
  - service-crew-service-green.yaml
  - deployment-marathon-service.yaml
  - service-marathon-service.yaml
  - deployment-marathon-service-green.yaml
  - service-marathon-service-green.yaml
  - deployment-media-service.yaml
  - service-media-service.yaml
  - deployment-media-service-green.yaml
  - service-media-service-green.yaml
  - deployment-notification-service.yaml
  - service-notification-service.yaml
  - deployment-notification-service-green.yaml
  - service-notification-service-green.yaml
  - deployment-running-record-service.yaml
  - service-running-record-service.yaml
  - deployment-running-record-service-green.yaml
  - service-running-record-service-green.yaml
  - deployment-shoe-service.yaml
  - service-shoe-service.yaml
  - deployment-shoe-service-green.yaml
  - service-shoe-service-green.yaml
  - deployment-ai-assistant-service.yaml
  - service-ai-assistant-service.yaml
  - deployment-ai-assistant-service-green.yaml
  - service-ai-assistant-service-green.yaml
  - configmap-ai-rag-service.yaml
  - deployment-ai-rag-service.yaml
  - service-ai-rag-service.yaml
  - deployment-ai-rag-service-green.yaml
  - service-ai-rag-service-green.yaml
  - configmap-ai-course-recommendation.yaml
  - deployment-ai-course-recommendation.yaml
  - service-ai-course-recommendation.yaml
  - deployment-ai-course-recommendation-green.yaml
  - service-ai-course-recommendation-green.yaml
  - configmap-ai-shoe-life.yaml
  - deployment-ai-shoe-life.yaml
  - service-ai-shoe-life.yaml
  - deployment-ai-shoe-life-green.yaml
  - service-ai-shoe-life-green.yaml
  - httproute-canary.yaml
  - httproute-canary-2.yaml
  - configmap-zap-baseline.yaml
  - cronjob-zap-baseline.yaml
  - networkpolicy-zap-baseline.yaml
