apiVersion: v1
kind: Service
metadata:
  name: dai-run-auth-web
  labels:
    app.kubernetes.io/name: dai-run-auth-web
    app.kubernetes.io/part-of: dai-run
    app.kubernetes.io/component: auth-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dai-run-auth-web
    dairun.io/track: blue
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
