apiVersion: v1
kind: Service
metadata:
  name: dai-run-frontend-green
  labels:
    app.kubernetes.io/name: dai-run-frontend-green
    app.kubernetes.io/part-of: dai-run
    app.kubernetes.io/component: frontend
    dairun.io/track: green
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dai-run-frontend-green
    dairun.io/track: green
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
