apiVersion: v1
data:
  AWS_REGION: ap-northeast-2
  DIR_ENVIRONMENT_TABLE_NAME: dir-environment
  INITIAL_LOOKBACK_HOURS: '72'
  OTEL_EXPORTER_OTLP_ENDPOINT: http://dir-otel-gateway-svc.dir-obsv-ns.svc.cluster.local:4318
  PGDATABASE: dai_run
  PGHOST: dir-postgresql-rw.dir-db-ns.svc.cluster.local
  PGPORT: '5432'
  PGSSL: 'true'
  PGSSL_REJECT_UNAUTHORIZED: 'false'
  POLL_INTERVAL_MS: '60000'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: dir-environment-dynamodb-consumer
    app.kubernetes.io/part-of: dai-run
  name: dir-environment-dynamodb-consumer-config
  namespace: dir-backend-ns
