apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dir-media
    app.kubernetes.io/part-of: dai-run
  name: dir-media-svc
  namespace: dir-backend-ns
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8113
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: dir-media
  sessionAffinity: None
  type: ClusterIP
