{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "labels": {
          "app.kubernetes.io/name": "dir-ai-assistant-service",
          "app.kubernetes.io/part-of": "dai-run"
        },
        "name": "dir-ai-assistant-service-svc",
        "namespace": "dir-ai-ns"
      },
      "spec": {
        "internalTrafficPolicy": "Cluster",
        "ports": [
          {
            "name": "http",
            "port": 8202,
            "protocol": "TCP",
            "targetPort": "http"
          }
        ],
        "selector": {
          "app.kubernetes.io/name": "dir-ai-assistant-service"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "labels": {
          "app.kubernetes.io/name": "dir-ai-assistant",
          "app.kubernetes.io/part-of": "dai-run"
        },
        "name": "dir-ai-assistant-svc",
        "namespace": "dir-ai-ns"
      },
      "spec": {
        "internalTrafficPolicy": "Cluster",
        "ports": [
          {
            "name": "http",
            "port": 8202,
            "protocol": "TCP",
            "targetPort": "http"
          }
        ],
        "selector": {
          "app.kubernetes.io/name": "dir-ai-assistant"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "labels": {
          "app.kubernetes.io/name": "dir-course-recommendation-service",
          "app.kubernetes.io/part-of": "dai-run"
        },
        "name": "dir-course-recommendation-service-svc",
        "namespace": "dir-ai-ns"
      },
      "spec": {
        "internalTrafficPolicy": "Cluster",
        "ports": [
          {
            "name": "http",
            "port": 8201,
            "protocol": "TCP",
            "targetPort": "http"
          }
        ],
        "selector": {
          "app.kubernetes.io/name": "dir-course-recommendation-service"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "labels": {
          "app.kubernetes.io/name": "dir-course-recommendation",
          "app.kubernetes.io/part-of": "dai-run"
        },
        "name": "dir-course-recommendation-svc",
        "namespace": "dir-ai-ns"
      },
      "spec": {
        "internalTrafficPolicy": "Cluster",
        "ports": [
          {
            "name": "http",
            "port": 8201,
            "protocol": "TCP",
            "targetPort": "http"
          }
        ],
        "selector": {
          "app.kubernetes.io/name": "dir-course-recommendation"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "labels": {
          "app.kubernetes.io/name": "dir-shoe-life-ai",
          "app.kubernetes.io/part-of": "dai-run"
        },
        "name": "dir-shoe-life-ai-svc",
        "namespace": "dir-ai-ns"
      },
      "spec": {
        "internalTrafficPolicy": "Cluster",
        "ports": [
          {
            "name": "http",
            "port": 8204,
            "protocol": "TCP",
            "targetPort": "http"
          }
        ],
        "selector": {
          "app.kubernetes.io/name": "dir-shoe-life-ai"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
      }
    }
  ],
  "kind": "List",
  "metadata": {}
}
