apiVersion: v1
data:
  AI_RAG_SERVICE_URL: http://dir-ai-assistant-svc.dir-ai-ns.svc.cluster.local:8202
  AI_RECOMMENDATION_SERVICE_URL: http://dir-course-recommendation-svc.dir-ai-ns.svc.cluster.local:8201
  APP_ENV: local
  APP_NAME: DAI RUN AI Course Recommendation API
  AWS_REGION: ap-northeast-2
  BEDROCK_MODEL_ID: arn:aws:bedrock:ap-northeast-2:311233338510:inference-profile/apac.amazon.nova-micro-v1:0
  COURSE_RECOMMENDATION_SERVICE_URL: http://dir-course-recommendation-service-svc.dir-ai-ns.svc.cluster.local:8201
  COURSE_SERVICE_URL: http://dir-course-svc.dir-backend-ns.svc.cluster.local:8102
  HOSTNAME: 0.0.0.0
  MEDIA_SERVICE_URL: http://dir-media-svc.dir-backend-ns.svc.cluster.local:8113
  NEXTAUTH_URL: https://dai-run.internal
  NEXT_TELEMETRY_DISABLED: '1'
  NODE_ENV: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://dir-otel-gateway-svc.dir-obsv-ns.svc.cluster.local:4318
  PGDATABASE: dai_run
  PGHOST: dir-postgresql-rw.dir-db-ns.svc.cluster.local
  PGPORT: '5432'
  PGSSLMODE: require
  PROMPT_VERSION: course-ai-v1
  SHOE_LIFE_AI_SERVICE_URL: http://dir-shoe-life-ai-svc.dir-ai-ns.svc.cluster.local:8204
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: dir-course-recommendation
    app.kubernetes.io/part-of: dai-run
  name: dir-course-recommendation-config
  namespace: dir-ai-ns

