apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dir-ai-ns
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - deployments.yaml
  - services.yaml
  - hpas.yaml
  - scaledobjects.yaml
  - networkpolicys.yaml
  - secretstore-dir-course-recommendation-shadow.yaml
  - externalsecret-dir-course-recommendation-shadow.yaml
  - networkpolicy-dir-course-recommendation-db-shadow.yaml
