apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-course-recommendation-shadow
  namespace: dir-ai-ns
  labels:
    app.kubernetes.io/name: dir-course-recommendation
    app.kubernetes.io/part-of: dai-run
    dairun.io/change-scope: db-shadow-canary
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
