apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-smoke-test
  namespace: dir-argocd-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dai-run-dev
  source:
    repoURL: http://10.20.0.253/dai-run/gitops.git
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dir-gitops-test-ns
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - Validate=true
      - ApplyOutOfSyncOnly=true



