apiVersion: v1
kind: ConfigMap
metadata:
  name: dai-run-ai-course-recommendation-config
  labels:
    app.kubernetes.io/name: dai-run-ai-course-recommendation
    app.kubernetes.io/part-of: dai-run
    app.kubernetes.io/component: ai-course-recommendation
data:
  AWS_REGION: ap-northeast-2
  BEDROCK_MODEL_ID: "arn:aws:bedrock:ap-northeast-2:970307871446:inference-profile/apac.amazon.nova-micro-v1:0"
