apiVersion: v1
kind: Service
metadata:
  name: dai-run-ai-course-recommendation
  labels:
    app.kubernetes.io/name: dai-run-ai-course-recommendation
    app.kubernetes.io/part-of: dai-run
    app.kubernetes.io/component: ai-course-recommendation
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dai-run-ai-course-recommendation
    dairun.io/track: blue
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
