apiVersion: v1
kind: Service
metadata:
  name: dai-run-media-service
  labels:
    app.kubernetes.io/name: dai-run-media-service
    app.kubernetes.io/part-of: dai-run
    app.kubernetes.io/component: media-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dai-run-media-service
    dairun.io/track: blue
  ports:
    - name: http
      port: 8113
      targetPort: http
      protocol: TCP
